waypoints:
-pose:
	position:
		x: -0.5
		y: -2.5
		z: 0.0
	orientation:
		x: 0.0
		y: 0.0
		z: -1.0 
		w: 0.0
-pose:
	position:
		x: -1.5
		y: 3.5
		z: 0.0
	orientation:
		x: 0.0
		y: 0.0
		z: -1.0 
		w: 1.0
-pose:
	position:
		x: -1.5
		y: 7.5
		z: 0.0
	orientation:
		x: 0.0
		y: 0.0
		z: -1.0 
		w: 1.0
-pose:
	position:
		x: 1.5
		y: 7.5
		z: 0.0
	orientation:
		x: 0.0
		y: 0.0
		z: 0.0 
		w: 1.0
-pose:
	position:
		x: 1.5
		y: 0.5
		z: 0.0
	orientation:
		x: 0.0
		y: 0.0
		z: 0.0 
		w: 1.0
-pose:
	position:
		x: 2.5
		y: -2.5
		z: 0.0
	orientation:
		x: 0.0
		y: 0.0
		z: 0.0 
		w: 1.0
